# Generated by Django 2.2.1 on 2019-05-11 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verfied'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='unique verfication uuid'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='agent status'),
        ),
    ]
