# Generated by Django 2.2.1 on 2019-05-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190511_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
